from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^my-content/$',
        views.MyContentView.as_view(),
        name='my-content'
    ),

    # Async file upload url
    # format:  /goals/<object_type>/<pk>/upload/
    # e.g. /goals/action/428/upload/
    # e.g. /goals/category/2/upload/
    url(
        r'^upload/(?P<object_type>\w+)/(?P<pk>\d+)/$',
        views.file_upload,
        name='file-upload'
    ),

    # Custom Packages
    url(
        r'^accept-enrollment/complete/$',
        views.AcceptEnrollmentCompleteView.as_view(),
        name='accept-enrollment-complete'
    ),
    url(
        r'^accept-enrollment/(?P<pk>\d+)/$',
        views.accept_enrollment,
        name='accept-enrollment'
    ),
    url(
        r'^packages/(?P<pk>\d+)/email/$',
        views.enrollment_cta_email,
        name='package-cta-email'
    ),
    url(
        r'^packages/(?P<pk>\d+)/report/$',
        views.package_report,
        name='package-report'
    ),
    url(
        r'^packages/(?P<pk>\d+)/reminder/$',
        views.enrollment_reminder,
        name='package-reminder'
    ),
    url(
        r'^packages/(?P<pk>\d+)/enroll/$',
        views.PackageEnrollmentView.as_view(),
        name='package-enroll'
    ),
    url(
        r'^packages/(?P<pk>\d+)/delete/$',
        views.PackageEnrollmentDeleteView.as_view(),
        name='package-enrollment-delete'
    ),
    url(
        r'^packages/(?P<pk>\d+)/calendar/$',
        views.package_calendar,
        name='package-calendar'
    ),
    url(
        r'^packages/(?P<package_id>\d+)/(?P<user_id>\d+)/$',
        views.package_enrollment_user_details,
        name='package-user-details'
    ),
    url(
        r'^packages/(?P<pk>\d+)/$',
        views.PackageDetailView.as_view(),
        name='package-detail'
    ),
    url(
        r'^packages/$',
        views.PackageListView.as_view(),
        name='package-list'
    ),

    # Create views
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/new-program/$',
        views.ProgramCreateView.as_view(),
        name='program-create'
    ),
    url(
        r'^new/organization/$',
        views.OrganizationCreateView.as_view(),
        name='organization-create'
    ),
    url(
        r'^new/categories/$',
        views.CategoryCreateView.as_view(),
        name='category-create'
    ),
    url(
        r'^new/goals/$',
        views.GoalCreateView.as_view(),
        name='goal-create'
    ),
    url(
        r'^new/behavior/$',
        views.BehaviorCreateView.as_view(),
        name='behavior-create'
    ),
    url(
        r'^new/action/$',
        views.ActionCreateView.as_view(),
        name='action-create'
    ),

    # Actions
    url(
        r'^actions/$',
        views.ActionListView.as_view(),
        name='action-list'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/disable-trigger/$',
        views.disable_trigger,
        name='action-disable-trigger'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.ActionPublishView.as_view(),
        name='action-publish'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.ActionTransferView.as_view(),
        name='action-transfer'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.ActionUpdateView.as_view(),
        name='action-update'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.ActionDeleteView.as_view(),
        name='action-delete'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.ActionDuplicateView.as_view(),
        name='action-duplicate'
    ),
    url(
        r'^actions/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.ActionDetailView.as_view(),
        name='action-detail'
    ),

    # Behaviors
    url(
        r'^behaviors/$',
        views.BehaviorListView.as_view(),
        name='behavior-list'
    ),
    url(
        r'^behaviors/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.BehaviorPublishView.as_view(),
        name='behavior-publish'
    ),
    url(
        r'^behaviors/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.BehaviorTransferView.as_view(),
        name='behavior-transfer'
    ),
    url(
        r'^behaviors/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.BehaviorUpdateView.as_view(),
        name='behavior-update'
    ),
    url(
        r'^behaviors/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.BehaviorDeleteView.as_view(),
        name='behavior-delete'
    ),
    url(
        r'^behaviors/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.BehaviorDuplicateView.as_view(),
        name='behavior-duplicate'
    ),
    url(
        r'^behaviors/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.BehaviorDetailView.as_view(),
        name='behavior-detail'
    ),

    # Triggers
    url(
        r'^triggers/$',
        views.TriggerListView.as_view(),
        name='trigger-list'
    ),
    url(
        r'^triggers/(?P<pk>\d+)/$',
        views.TriggerDetailView.as_view(),
        name='trigger-detail'
    ),

    # Goals
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.GoalPublishView.as_view(),
        name='goal-publish'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.GoalTransferView.as_view(),
        name='goal-transfer'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.GoalUpdateView.as_view(),
        name='goal-update'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.GoalDeleteView.as_view(),
        name='goal-delete'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.GoalDuplicateView.as_view(),
        name='goal-duplicate'
    ),
    url(
        r'^goals/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.GoalDetailView.as_view(),
        name='goal-detail'
    ),
    url(
        r'^goals/$',
        views.GoalListView.as_view(),
        name='goal-list'
    ),

    # Categories
    url(
        r'^categories/$',
        views.CategoryListView.as_view(),
        name='category-list'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/publish/$',
        views.CategoryPublishView.as_view(),
        name='category-publish'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/transfer/$',
        views.CategoryTransferView.as_view(),
        name='category-transfer'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/update/$',
        views.CategoryUpdateView.as_view(),
        name='category-update'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/delete/$',
        views.CategoryDeleteView.as_view(),
        name='category-delete'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate-all/$',
        views.duplicate_content,
        name='duplicate-content'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/duplicate/$',
        views.CategoryDuplicateView.as_view(),
        name='category-duplicate'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/reset-triggers/$',
        views.reset_default_triggers_in_category,
        name='category-reset-triggers'
    ),
    url(
        r'^categories/(?P<pk>\d+)-(?P<title_slug>.+)/$',
        views.CategoryDetailView.as_view(),
        name='category-detail'
    ),

    # Organizations / Programs
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/update/$',
        views.ProgramUpdateView.as_view(),
        name='program-update'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/delete/$',
        views.ProgramDeleteView.as_view(),
        name='program-delete'
    ),
    url(
        r'^organizations/(?P<organization_id>\d+)-(?P<organization_name_slug>.+)/(?P<pk>\d+)-(?P<name_slug>.+)/$',
        views.ProgramDetailView.as_view(),
        name='program-detail'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/update/$',
        views.OrganizationUpdateView.as_view(),
        name='organization-update'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/delete/$',
        views.OrganizationDeleteView.as_view(),
        name='organization-delete'
    ),
    url(
        r'^organizations/(?P<pk>\d+)-(?P<name_slug>.+)/$',
        views.OrganizationDetailView.as_view(),
        name='organization-detail'
    ),
    url(
        r'^programs/$',
        views.ProgramListView.as_view(),
        name='program-list'
    ),
    url(
        r'^organizations/$',
        views.OrganizationListView.as_view(),
        name='organization-list'
    ),

    # Misc Debugging & Reports.
    url(
        r'^batch-assign-keywords/$',
        views.admin_batch_assign_keywords,
        name='batch-assign-keywords'
    ),
    url(
        r'^debug/$',
        views.DebugToolsView.as_view(),
        name='debug_tools'
    ),
    url(
        r'^debug-sequence/$',
        views.debug_sequence,
        name='debug_sequence'
    ),
    url(
        r'^debug-feed/$',
        views.debug_feed,
        name='debug_feed'
    ),
    url(
        r'^debug-priority-notifications/$',
        views.debug_priority_notifications,
        name='debug_priority_notifications'
    ),
    url(
        r'^debug-notifications/$',
        views.debug_notifications,
        name='debug_notifications'
    ),
    url(
        r'^debug-progress/$',
        views.debug_progress,
        name='debug_progress'
    ),
    url(
        r'^reports/organization/(?P<pk>\d+)/$',
        views.report_organization,
        name='report-organization'
    ),
    url(
        r'^reports/organization/$',
        views.report_organization,
        name='report-organization'
    ),
    url(
        r'^reports/triggers/$',
        views.report_triggers,
        name='report-triggers'
    ),
    url(
        r'^reports/popular/$',
        views.ReportPopularView.as_view(),
        name='report-popular'
    ),
    url(
        r'^reports/actions/$',
        views.report_actions,
        name='report-actions'
    ),
    url(
        r'^reports/authors/$',
        views.report_authors,
        name='report-authors'
    ),
    url(
        r'^reports/engagement/$',
        views.report_engagement,
        name='report-engagement'
    ),
    url(
        r'^reports/$',
        views.ReportsView.as_view(),
        name='reports'
    ),
]
