# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_auto_20160624_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
