# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-06 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_image',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
