# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
