# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='digest',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(db_index=True, default='', max_length=256),
        ),
    ]
