# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Message recipient(s)', related_name='chatmessages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(help_text='Message sender', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
