# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 21:38
from __future__ import unicode_literals
from django.db import migrations


def set_recipients(apps, schema_editor):
    """Set recipients based on room name;
    So far we've only had 1-1 messages (no groups).
    """
    ChatMessage = apps.get_model("chat", "ChatMessage")
    User = apps.get_model("auth", "User")

    for msg in ChatMessage.objects.all():
        if msg.room.startswith("chat-"):
            ids = msg.room[len("chat-"):].split('-')
            users = User.objects.filter(pk__in=ids)
            users = users.exclude(pk=msg.user.id)
            for user in users:
                msg.recipients.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170210_2121'),
    ]

    operations = [
        migrations.RunPython(set_recipients),
    ]
