# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 01:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officehours', '0002_auto_20170123_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officehours',
            options={'ordering': ['created_on'], 'verbose_name': 'Office Hours', 'verbose_name_plural': 'Office Hours'},
        ),
        migrations.RemoveField(
            model_name='officehours',
            name='days',
        ),
        migrations.RemoveField(
            model_name='officehours',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='officehours',
            name='to_time',
        ),
        migrations.AddField(
            model_name='officehours',
            name='schedule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
