# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 16:30
from __future__ import unicode_literals
from django.db import migrations


def refactor_schedule_times(apps, schema_editor):
    """Change the JSON data in OfficeHours.schedule so that it goes from this:

        {'DAY': [[from, to], [from, to], ... ]}

    To this: (a list of objects for times)

    {
      'DAY': [{"from": "...", "to": "..."}, ... ],
      ...
      'Friday': [
          {"from": "15:30", "to": "16:30"},
          {"from": "14:30", "to": "15:00"},
      ]
    }

    """
    OfficeHours = apps.get_model("officehours", "OfficeHours")
    for obj in OfficeHours.objects.filter(schedule__gt={}):
        new_schedule = {}
        for day, hours_list in obj.schedule.items():
            new_schedule[day] = [
                {'from': from_time, 'to': to_time}
                for from_time, to_time in hours_list
            ]
        obj.schedule = new_schedule
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('officehours', '0003_auto_20170201_0133'),
    ]

    operations = [
        migrations.RunPython(refactor_schedule_times),
    ]
