# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours', '0004_revise_schedule_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
