# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-09 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours', '0005_auto_20170209_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
