# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0160_auto_20160809_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='serialized_action',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='serialized_behavior',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='serialized_custom_trigger',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='serialized_primary_category',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='serialized_primary_goal',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='serialized_trigger',
        ),
    ]
