# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0161_auto_20160822_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='goals.Category'),
        ),
    ]
