# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 20:47
from __future__ import unicode_literals

from django.db import migrations


def copy_goal_categories(apps, schema_editor):
    Behavior = apps.get_model("goals", "Behavior")
    for behavior in Behavior.objects.all():
        for goal in behavior.goals.all():
            for category in goal.categories.all():
                behavior.categories.add(category)
        behavior.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0162_behavior_categories'),
    ]

    operations = [
        migrations.RunPython(copy_goal_categories),
    ]
