# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0163_add_behavior_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='categories',
            field=models.ManyToManyField(blank=True, to='goals.Category'),
        ),
    ]
