# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0166_auto_20160902_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customactionfeedback',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
        ),
        migrations.AlterField(
            model_name='customactionfeedback',
            name='customgoal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.CustomGoal'),
        ),
    ]
