# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0167_auto_20160902_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='engagement_15_days',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='engagement_30_days',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='engagement_60_days',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
