# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0169_remove_dailyprogress_behaviors_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='action_buckets_checkup',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='action_buckets_core',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='action_buckets_helper',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='action_buckets_prep',
        ),
    ]
