# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0173_auto_20160921_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='goals',
            field=models.ManyToManyField(to='goals.Goal'),
        ),
    ]
