# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0173_auto_20160921_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='goals',
            field=models.ManyToManyField(to='goals.Goal'),
        ),
        migrations.AlterField(
            model_name='action',
            name='behavior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Behavior', verbose_name='behavior'),
        ),
    ]
