# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 20:05
from __future__ import unicode_literals
from django.db import migrations


def copy_behavior_descriptions_to_actions(apps, schema_editor):
    """For each Action, copy it's parent behavior's description
    into the Action.more_info fields. If we have existing Action.more_info
    content, we'll move that into the Action's notes field.

    """
    Action = apps.get_model("goals", "Action")
    for action in Action.objects.all():
        if action.more_info:
            action.notes += "\n---- more_info ----\n{}".format(action.more_info)
        action.more_info = action.behavior.description
        action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0175_connect_actions_to_goals'),
    ]

    operations = [
        migrations.RunPython(copy_behavior_descriptions_to_actions),
    ]
