# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0176_copy_behavior_descriptions_to_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprogress',
            name='behaviors_total',
        ),
    ]
