# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 17:05
from __future__ import unicode_literals
from django.db import migrations


def reorder_actions_sequence_values(apps, schema_editor):
    """
    We're gonna get rid of Behaviors, however, Action's sequence orders
    are based on their parent behavior. So... let's revise those values
    so all actions retain the same order.

    """
    Action = apps.get_model("goals", "Action")
    Behavior = apps.get_model("goals", "Behavior")

    previous = 0
    for behavior in Behavior.objects.all().order_by('sequence_order'):
        actions = Action.objects.filter(behavior__id=behavior.id).order_by('sequence_order')
        for action in actions:
            if action.sequence_order < previous:
                action.sequence_order = previous
                action.save()
            previous = max([action.sequence_order, previous])


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0177_remove_dailyprogress_behaviors_total'),
    ]

    operations = [
        migrations.RunPython(reorder_actions_sequence_values)
    ]
