# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 17:05
from __future__ import unicode_literals
from django.db import migrations


def reorder_actions_sequence_values(apps, schema_editor):
    """
    We're gonna get rid of Behaviors, however, Action's sequence orders
    are based on their parent behavior. So... let's revise those values
    so all actions retain the same order.

    """
    Action = apps.get_model("goals", "Action")
    Behavior = apps.get_model("goals", "Behavior")
    Category = apps.get_model("goals", "Category")

    for cat in Category.objects.all():
        for goal in cat.goal_set.all().order_by('sequence_order'):

            prev_behavior = 0
            max_action_seq = 0

            behaviors = Behavior.objects.filter(goals__pk=goal.id)
            for behavior in behaviors.order_by('sequence_order'):

                offset = 0
                if behavior.sequence_order > prev_behavior:
                    offset = max_action_seq

                actions = Action.objects.filter(behavior__id=behavior.id)
                for action in actions.order_by('sequence_order'):

                    if behavior.sequence_order > prev_behavior:
                        action.sequence_order += offset
                        action.save()

                    if action.sequence_order > max_action_seq:
                        max_action_seq = action.sequence_order

                prev_behavior = behavior.sequence_order


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0177_remove_dailyprogress_behaviors_total'),
    ]

    operations = [
        migrations.RunPython(reorder_actions_sequence_values)
    ]
