# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0178_reorder_action_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='userbehavior',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='custom_trigger',
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='user',
        ),
        migrations.RemoveField(
            model_name='action',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='behaviors_count',
        ),
        migrations.AlterField(
            model_name='action',
            name='default_trigger',
            field=models.OneToOneField(blank=True, help_text='A trigger/reminder for this action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_default', to='goals.Trigger'),
        ),
        migrations.AlterField(
            model_name='action',
            name='sequence_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Order/number of action in stepwise sequence.'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='custom_trigger',
            field=models.ForeignKey(blank=True, help_text='A User-defined trigger for this action', null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Trigger'),
        ),
        migrations.DeleteModel(
            name='Behavior',
        ),
        migrations.DeleteModel(
            name='UserBehavior',
        ),
    ]
